# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        stages: [commit]
        language: system
        entry: cd backend && docker-compose run --rm web isort
        types: [python]

    -   id: black
        name: black
        language_version: python3.7
        stages: [commit]
        language: system
        entry: cd backend && docker-compose run --rm black
        types: [python]

    -   id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: cd backend && docker-compose run --rm flake8
        types: [python]
        exclude: setup.py

