version: '3'

services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    ports:
      - "54343:5432"

  redis:
    image: "redis:alpine"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"

  web:
    build: 
      context: .
    command: >
      sh -c "
        python src/manage.py migrate &&
        python src/manage.py runserver 0.0.0.0:8123
      "
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=password
    restart: on-failure
    volumes:
      - .:/home/appuser/src
    ports:
      - "8123:8123"
    depends_on:
      - db
      - redis
      - adminer
    links:
      - db:db
      - redis:redis

