# Generated by Django 2.2.12 on 2020-04-03 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('organizers', models.ManyToManyField(related_name='organizers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due', models.DateField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('upper_limit', models.PositiveSmallIntegerField(verbose_name='Maximum allowed matches')),
                ('lower_limit', models.PositiveSmallIntegerField(verbose_name='Minimum needed matches')),
                ('need_type', models.CharField(choices=[('ND', 'Needs'), ('NC', 'Necessities'), ('RS', 'Resources'), ('VO', 'Volunteer Opportunities')], default='ND', max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='needs.Organization')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due', models.DateField()),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need', to='needs.Need')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['organization', 'due'], name='needs_need_organiz_901000_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['volunteer', 'due'], name='needs_match_volunte_645d07_idx'),
        ),
    ]
