# Generated by Django 2.2.12 on 2020-04-05 02:02

import app.needs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='due',
            field=models.DateField(blank=True, null=True, validators=[app.needs.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='need',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='lower_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimum needed matches'),
        ),
        migrations.AlterField(
            model_name='need',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='need',
            name='upper_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum allowed matches'),
        ),
    ]
