# Generated by Django 2.2.12 on 2020-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_auto_20200405_0202'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='needs_match_volunte_645d07_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='due',
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['volunteer'], name='needs_match_volunte_469790_idx'),
        ),
    ]
