# Generated by Django 2.2.12 on 2020-04-12 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_auto_20200407_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='need_type',
            field=models.CharField(choices=[('NEEDS', 'Needs'), ('NECESSITIES', 'Necessities'), ('RESOURCES', 'Resources'), ('VOLUNTEER', 'Volunteer Opportunities')], default='NEEDS', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizers', to=settings.AUTH_USER_MODEL),
        ),
    ]
