# Generated by Django 2.2.12 on 2020-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0005_auto_20200412_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='category',
            field=models.CharField(default='Materials', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need',
            name='city',
            field=models.CharField(default='San Juan', max_length=40),
            preserve_default=False,
        ),
    ]
