# Generated by Django 2.2.12 on 2020-04-30 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('needs', '0006_auto_20200412_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='volunteers',
            field=models.ManyToManyField(blank=True, through='needs.Match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='needs.Need'),
        ),
        migrations.AlterField(
            model_name='match',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='need',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='needs.Organization'),
        ),
        migrations.AlterField(
            model_name='need',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
