# Generated by Django 2.2.9 on 2020-02-25 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organizers",
            field=models.ManyToManyField(
                related_name="organizers", to=settings.AUTH_USER_MODEL
            ),
        )
    ]
