# Generated by Django 3.0.3 on 2020-03-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0002_organization_organizers")]

    operations = [
        migrations.AlterField(
            model_name="organization", name="description", field=models.TextField()
        )
    ]
