# Generated by Django 2.2.9 on 2020-02-25 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("matches", "0001_initial"), ("needs", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="match",
            name="need",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="need",
                to="needs.Need",
            ),
        )
    ]
