# Generated by Django 2.2.9 on 2020-02-25 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0002_match_need"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="volunteer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["volunteer", "due"], name="matches_mat_volunte_2bdf65_idx"
            ),
        ),
    ]
