# Generated by Django 2.2.9 on 2020-02-25 23:38

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due", models.DateField()),
                ("lat", models.DecimalField(decimal_places=6, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=10)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "upper_limit",
                    models.PositiveSmallIntegerField(
                        verbose_name="Maximum allowed matches"
                    ),
                ),
                (
                    "lower_limit",
                    models.PositiveSmallIntegerField(
                        verbose_name="Minimum needed matches"
                    ),
                ),
            ],
            options={"ordering": ["-due"]},
        )
    ]
