# Generated by Django 2.2.9 on 2020-02-25 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("needs", "0001_initial"), ("organizations", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="need",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to="organizations.Organization",
            ),
        )
    ]
