# Generated by Django 2.2.9 on 2020-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("needs", "0003_auto_20200225_2338")]

    operations = [
        migrations.AlterModelOptions(
            name="need",
            options={"ordering": ["-due"], "verbose_name_plural": "Matches"},
        )
    ]
