# Generated by Django 2.2.9 on 2020-02-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("needs", "0004_auto_20200227_1447")]

    operations = [
        migrations.AlterModelOptions(name="need", options={"ordering": ["-due"]})
    ]
