# Generated by Django 3.0.3 on 2020-03-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("needs", "0005_auto_20200227_1448")]

    operations = [
        migrations.AddField(
            model_name="need",
            name="need_type",
            field=models.CharField(
                choices=[
                    ("ND", "Needs"),
                    ("NC", "Necessities"),
                    ("RS", "Resources"),
                    ("VO", "Volunteer Opportunities"),
                ],
                default="ND",
                max_length=2,
            ),
        )
    ]
